name: CD

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: checkout
        uses: actions/checkout@v2
      # set up golang
      - name: set up golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      # set up docker
      - name: set up docker
        uses: docker/setup-buildx-action@v1
      # docker login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GCR_PERSONAL_TOKEN }}
      # test
      - name: test
        run: go test ./... -v
      # build and push image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/golang-ci-cd:latest
