name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup-go
      - name: set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      # checkout
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # test
      - name: test
        run: go test -v -coverprofile=cover.out -covermode=atomic ./...
      # codecov
      # - name: codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: cover.out
      # self-coverage
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: coverage
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install golang.org/x/lint/golint
          golint ./... | reviewdog -efm="%f:%l:%c: %m" -diff="git diff FETCH_HEAD"
          git diff origin/feature/test-base...origin/feature/test-diff --name-only > f.txt
          head -n 1 cover.out > cover2.out
          grep -f f.txt cover.out >> cover2.out
          cat cover2.out
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@1.0.2
        with:
          message: "Example of message2 !"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
