name: Draft

on:
  pull_request:
    types: [ready_for_review, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: draft
        run: echo ${{ github.event.pull_request.draft }}
